### ISSUE TITLE
Docker Compose Example

### ISSUE THREAD

**Issue by aminnairi** [vlang/docker#7]
Hi there,

I noticed that there is no Docker Compose example.

It would be nice since Docker Compose is a tool that leverages Docker.

I can help with a pull request if this is okay for the maintainers of this repository. Just checking in before submitting anything.

**Comment by annymosse** [comment]
@aminnairi why not ? 😉 any contribution are helpful to grab more contributes and communities.
i believe in HELP EVEN BY SINGLE WORD.

**Comment by aminnairi** [comment]
Resolved in #7 seemingly.
